-- -------------------------------------------------------------
--
-- Module: filter
-- Generated by MATLAB(R) 9.1 and the Filter Design HDL Coder 3.1.
-- Generated on: 2020-02-26 20:04:35
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- FIRAdderStyle: tree
-- TargetDirectory: C:\Xilinx\Workspace\ADS8694_v1\src\FIR_filter
-- TestBenchStimulus: impulse step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 123
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    real; -- double
         filter_out                      :   OUT   real  -- double
         );

END filter;


----------------------------------------------------------------
--Module Architecture: filter
----------------------------------------------------------------
ARCHITECTURE rtl OF filter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF real; -- double
  -- Constants
  CONSTANT coeff1                         : real := -1.7088228505061597E-02; -- double
  CONSTANT coeff2                         : real := -2.8017598203808358E-03; -- double
  CONSTANT coeff3                         : real := -3.0013734420005910E-03; -- double
  CONSTANT coeff4                         : real := -3.1930522722416303E-03; -- double
  CONSTANT coeff5                         : real := -3.3681978379913016E-03; -- double
  CONSTANT coeff6                         : real := -3.5298708114330410E-03; -- double
  CONSTANT coeff7                         : real := -3.6699712682051197E-03; -- double
  CONSTANT coeff8                         : real := -3.7895108925839905E-03; -- double
  CONSTANT coeff9                         : real := -3.8836389354557112E-03; -- double
  CONSTANT coeff10                        : real := -3.9495786895529812E-03; -- double
  CONSTANT coeff11                        : real := -3.9843686587501806E-03; -- double
  CONSTANT coeff12                        : real := -3.9901144871017646E-03; -- double
  CONSTANT coeff13                        : real := -3.9568019146254269E-03; -- double
  CONSTANT coeff14                        : real := -3.8891027218164800E-03; -- double
  CONSTANT coeff15                        : real := -3.7803972344691468E-03; -- double
  CONSTANT coeff16                        : real := -3.6329735649248142E-03; -- double
  CONSTANT coeff17                        : real := -3.4396001840352746E-03; -- double
  CONSTANT coeff18                        : real := -3.2030675459085532E-03; -- double
  CONSTANT coeff19                        : real := -2.9177047221879437E-03; -- double
  CONSTANT coeff20                        : real := -2.5876257545252067E-03; -- double
  CONSTANT coeff21                        : real := -2.2051975195941593E-03; -- double
  CONSTANT coeff22                        : real := -1.7763391334000209E-03; -- double
  CONSTANT coeff23                        : real := -1.2959844374207015E-03; -- double
  CONSTANT coeff24                        : real := -7.6923416941106584E-04; -- double
  CONSTANT coeff25                        : real := -1.9189863458522242E-04; -- double
  CONSTANT coeff26                        : real := 4.3015838064203307E-04; -- double
  CONSTANT coeff27                        : real := 1.1010020192080507E-03; -- double
  CONSTANT coeff28                        : real := 1.8152868692190888E-03; -- double
  CONSTANT coeff29                        : real := 2.5788532637755044E-03; -- double
  CONSTANT coeff30                        : real := 3.3828861026615337E-03; -- double
  CONSTANT coeff31                        : real := 4.2291904589336782E-03; -- double
  CONSTANT coeff32                        : real := 5.1104136076382924E-03; -- double
  CONSTANT coeff33                        : real := 6.0243742230416935E-03; -- double
  CONSTANT coeff34                        : real := 6.9636723861808032E-03; -- double
  CONSTANT coeff35                        : real := 7.9318133338504727E-03; -- double
  CONSTANT coeff36                        : real := 8.9248300796081221E-03; -- double
  CONSTANT coeff37                        : real := 9.9468874080078738E-03; -- double
  CONSTANT coeff38                        : real := 1.0977433421961324E-02; -- double
  CONSTANT coeff39                        : real := 1.1997643083634105E-02; -- double
  CONSTANT coeff40                        : real := 1.3053201942857440E-02; -- double
  CONSTANT coeff41                        : real := 1.4092015842969390E-02; -- double
  CONSTANT coeff42                        : real := 1.5128683341926057E-02; -- double
  CONSTANT coeff43                        : real := 1.6158292983245649E-02; -- double
  CONSTANT coeff44                        : real := 1.7170519386407054E-02; -- double
  CONSTANT coeff45                        : real := 1.8165692593409551E-02; -- double
  CONSTANT coeff46                        : real := 1.9135639906102699E-02; -- double
  CONSTANT coeff47                        : real := 2.0073418189212523E-02; -- double
  CONSTANT coeff48                        : real := 2.0981925431709035E-02; -- double
  CONSTANT coeff49                        : real := 2.1849029723520198E-02; -- double
  CONSTANT coeff50                        : real := 2.2668378671580225E-02; -- double
  CONSTANT coeff51                        : real := 2.3445174290938092E-02; -- double
  CONSTANT coeff52                        : real := 2.4167303791084654E-02; -- double
  CONSTANT coeff53                        : real := 2.4834438260071062E-02; -- double
  CONSTANT coeff54                        : real := 2.5438644725316019E-02; -- double
  CONSTANT coeff55                        : real := 2.5982493535940267E-02; -- double
  CONSTANT coeff56                        : real := 2.6459516158686251E-02; -- double
  CONSTANT coeff57                        : real := 2.6870488659126984E-02; -- double
  CONSTANT coeff58                        : real := 2.7206714629683493E-02; -- double
  CONSTANT coeff59                        : real := 2.7472684520942259E-02; -- double
  CONSTANT coeff60                        : real := 2.7660415335691278E-02; -- double
  CONSTANT coeff61                        : real := 2.7774768409633499E-02; -- double
  CONSTANT coeff62                        : real := 2.7811098415134974E-02; -- double
  CONSTANT coeff63                        : real := 2.7774768409633499E-02; -- double
  CONSTANT coeff64                        : real := 2.7660415335691278E-02; -- double
  CONSTANT coeff65                        : real := 2.7472684520942259E-02; -- double
  CONSTANT coeff66                        : real := 2.7206714629683493E-02; -- double
  CONSTANT coeff67                        : real := 2.6870488659126984E-02; -- double
  CONSTANT coeff68                        : real := 2.6459516158686251E-02; -- double
  CONSTANT coeff69                        : real := 2.5982493535940267E-02; -- double
  CONSTANT coeff70                        : real := 2.5438644725316019E-02; -- double
  CONSTANT coeff71                        : real := 2.4834438260071062E-02; -- double
  CONSTANT coeff72                        : real := 2.4167303791084654E-02; -- double
  CONSTANT coeff73                        : real := 2.3445174290938092E-02; -- double
  CONSTANT coeff74                        : real := 2.2668378671580225E-02; -- double
  CONSTANT coeff75                        : real := 2.1849029723520198E-02; -- double
  CONSTANT coeff76                        : real := 2.0981925431709035E-02; -- double
  CONSTANT coeff77                        : real := 2.0073418189212523E-02; -- double
  CONSTANT coeff78                        : real := 1.9135639906102699E-02; -- double
  CONSTANT coeff79                        : real := 1.8165692593409551E-02; -- double
  CONSTANT coeff80                        : real := 1.7170519386407054E-02; -- double
  CONSTANT coeff81                        : real := 1.6158292983245649E-02; -- double
  CONSTANT coeff82                        : real := 1.5128683341926057E-02; -- double
  CONSTANT coeff83                        : real := 1.4092015842969390E-02; -- double
  CONSTANT coeff84                        : real := 1.3053201942857440E-02; -- double
  CONSTANT coeff85                        : real := 1.1997643083634105E-02; -- double
  CONSTANT coeff86                        : real := 1.0977433421961324E-02; -- double
  CONSTANT coeff87                        : real := 9.9468874080078738E-03; -- double
  CONSTANT coeff88                        : real := 8.9248300796081221E-03; -- double
  CONSTANT coeff89                        : real := 7.9318133338504727E-03; -- double
  CONSTANT coeff90                        : real := 6.9636723861808032E-03; -- double
  CONSTANT coeff91                        : real := 6.0243742230416935E-03; -- double
  CONSTANT coeff92                        : real := 5.1104136076382924E-03; -- double
  CONSTANT coeff93                        : real := 4.2291904589336782E-03; -- double
  CONSTANT coeff94                        : real := 3.3828861026615337E-03; -- double
  CONSTANT coeff95                        : real := 2.5788532637755044E-03; -- double
  CONSTANT coeff96                        : real := 1.8152868692190888E-03; -- double
  CONSTANT coeff97                        : real := 1.1010020192080507E-03; -- double
  CONSTANT coeff98                        : real := 4.3015838064203307E-04; -- double
  CONSTANT coeff99                        : real := -1.9189863458522242E-04; -- double
  CONSTANT coeff100                       : real := -7.6923416941106584E-04; -- double
  CONSTANT coeff101                       : real := -1.2959844374207015E-03; -- double
  CONSTANT coeff102                       : real := -1.7763391334000209E-03; -- double
  CONSTANT coeff103                       : real := -2.2051975195941593E-03; -- double
  CONSTANT coeff104                       : real := -2.5876257545252067E-03; -- double
  CONSTANT coeff105                       : real := -2.9177047221879437E-03; -- double
  CONSTANT coeff106                       : real := -3.2030675459085532E-03; -- double
  CONSTANT coeff107                       : real := -3.4396001840352746E-03; -- double
  CONSTANT coeff108                       : real := -3.6329735649248142E-03; -- double
  CONSTANT coeff109                       : real := -3.7803972344691468E-03; -- double
  CONSTANT coeff110                       : real := -3.8891027218164800E-03; -- double
  CONSTANT coeff111                       : real := -3.9568019146254269E-03; -- double
  CONSTANT coeff112                       : real := -3.9901144871017646E-03; -- double
  CONSTANT coeff113                       : real := -3.9843686587501806E-03; -- double
  CONSTANT coeff114                       : real := -3.9495786895529812E-03; -- double
  CONSTANT coeff115                       : real := -3.8836389354557112E-03; -- double
  CONSTANT coeff116                       : real := -3.7895108925839905E-03; -- double
  CONSTANT coeff117                       : real := -3.6699712682051197E-03; -- double
  CONSTANT coeff118                       : real := -3.5298708114330410E-03; -- double
  CONSTANT coeff119                       : real := -3.3681978379913016E-03; -- double
  CONSTANT coeff120                       : real := -3.1930522722416303E-03; -- double
  CONSTANT coeff121                       : real := -3.0013734420005910E-03; -- double
  CONSTANT coeff122                       : real := -2.8017598203808358E-03; -- double
  CONSTANT coeff123                       : real := -1.7088228505061597E-02; -- double

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 122) := (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0, 0.0); -- double
  SIGNAL product123                       : real := 0.0; -- double
  SIGNAL product122                       : real := 0.0; -- double
  SIGNAL product121                       : real := 0.0; -- double
  SIGNAL product120                       : real := 0.0; -- double
  SIGNAL product119                       : real := 0.0; -- double
  SIGNAL product118                       : real := 0.0; -- double
  SIGNAL product117                       : real := 0.0; -- double
  SIGNAL product116                       : real := 0.0; -- double
  SIGNAL product115                       : real := 0.0; -- double
  SIGNAL product114                       : real := 0.0; -- double
  SIGNAL product113                       : real := 0.0; -- double
  SIGNAL product112                       : real := 0.0; -- double
  SIGNAL product111                       : real := 0.0; -- double
  SIGNAL product110                       : real := 0.0; -- double
  SIGNAL product109                       : real := 0.0; -- double
  SIGNAL product108                       : real := 0.0; -- double
  SIGNAL product107                       : real := 0.0; -- double
  SIGNAL product106                       : real := 0.0; -- double
  SIGNAL product105                       : real := 0.0; -- double
  SIGNAL product104                       : real := 0.0; -- double
  SIGNAL product103                       : real := 0.0; -- double
  SIGNAL product102                       : real := 0.0; -- double
  SIGNAL product101                       : real := 0.0; -- double
  SIGNAL product100                       : real := 0.0; -- double
  SIGNAL product99                        : real := 0.0; -- double
  SIGNAL product98                        : real := 0.0; -- double
  SIGNAL product97                        : real := 0.0; -- double
  SIGNAL product96                        : real := 0.0; -- double
  SIGNAL product95                        : real := 0.0; -- double
  SIGNAL product94                        : real := 0.0; -- double
  SIGNAL product93                        : real := 0.0; -- double
  SIGNAL product92                        : real := 0.0; -- double
  SIGNAL product91                        : real := 0.0; -- double
  SIGNAL product90                        : real := 0.0; -- double
  SIGNAL product89                        : real := 0.0; -- double
  SIGNAL product88                        : real := 0.0; -- double
  SIGNAL product87                        : real := 0.0; -- double
  SIGNAL product86                        : real := 0.0; -- double
  SIGNAL product85                        : real := 0.0; -- double
  SIGNAL product84                        : real := 0.0; -- double
  SIGNAL product83                        : real := 0.0; -- double
  SIGNAL product82                        : real := 0.0; -- double
  SIGNAL product81                        : real := 0.0; -- double
  SIGNAL product80                        : real := 0.0; -- double
  SIGNAL product79                        : real := 0.0; -- double
  SIGNAL product78                        : real := 0.0; -- double
  SIGNAL product77                        : real := 0.0; -- double
  SIGNAL product76                        : real := 0.0; -- double
  SIGNAL product75                        : real := 0.0; -- double
  SIGNAL product74                        : real := 0.0; -- double
  SIGNAL product73                        : real := 0.0; -- double
  SIGNAL product72                        : real := 0.0; -- double
  SIGNAL product71                        : real := 0.0; -- double
  SIGNAL product70                        : real := 0.0; -- double
  SIGNAL product69                        : real := 0.0; -- double
  SIGNAL product68                        : real := 0.0; -- double
  SIGNAL product67                        : real := 0.0; -- double
  SIGNAL product66                        : real := 0.0; -- double
  SIGNAL product65                        : real := 0.0; -- double
  SIGNAL product64                        : real := 0.0; -- double
  SIGNAL product63                        : real := 0.0; -- double
  SIGNAL product62                        : real := 0.0; -- double
  SIGNAL product61                        : real := 0.0; -- double
  SIGNAL product60                        : real := 0.0; -- double
  SIGNAL product59                        : real := 0.0; -- double
  SIGNAL product58                        : real := 0.0; -- double
  SIGNAL product57                        : real := 0.0; -- double
  SIGNAL product56                        : real := 0.0; -- double
  SIGNAL product55                        : real := 0.0; -- double
  SIGNAL product54                        : real := 0.0; -- double
  SIGNAL product53                        : real := 0.0; -- double
  SIGNAL product52                        : real := 0.0; -- double
  SIGNAL product51                        : real := 0.0; -- double
  SIGNAL product50                        : real := 0.0; -- double
  SIGNAL product49                        : real := 0.0; -- double
  SIGNAL product48                        : real := 0.0; -- double
  SIGNAL product47                        : real := 0.0; -- double
  SIGNAL product46                        : real := 0.0; -- double
  SIGNAL product45                        : real := 0.0; -- double
  SIGNAL product44                        : real := 0.0; -- double
  SIGNAL product43                        : real := 0.0; -- double
  SIGNAL product42                        : real := 0.0; -- double
  SIGNAL product41                        : real := 0.0; -- double
  SIGNAL product40                        : real := 0.0; -- double
  SIGNAL product39                        : real := 0.0; -- double
  SIGNAL product38                        : real := 0.0; -- double
  SIGNAL product37                        : real := 0.0; -- double
  SIGNAL product36                        : real := 0.0; -- double
  SIGNAL product35                        : real := 0.0; -- double
  SIGNAL product34                        : real := 0.0; -- double
  SIGNAL product33                        : real := 0.0; -- double
  SIGNAL product32                        : real := 0.0; -- double
  SIGNAL product31                        : real := 0.0; -- double
  SIGNAL product30                        : real := 0.0; -- double
  SIGNAL product29                        : real := 0.0; -- double
  SIGNAL product28                        : real := 0.0; -- double
  SIGNAL product27                        : real := 0.0; -- double
  SIGNAL product26                        : real := 0.0; -- double
  SIGNAL product25                        : real := 0.0; -- double
  SIGNAL product24                        : real := 0.0; -- double
  SIGNAL product23                        : real := 0.0; -- double
  SIGNAL product22                        : real := 0.0; -- double
  SIGNAL product21                        : real := 0.0; -- double
  SIGNAL product20                        : real := 0.0; -- double
  SIGNAL product19                        : real := 0.0; -- double
  SIGNAL product18                        : real := 0.0; -- double
  SIGNAL product17                        : real := 0.0; -- double
  SIGNAL product16                        : real := 0.0; -- double
  SIGNAL product15                        : real := 0.0; -- double
  SIGNAL product14                        : real := 0.0; -- double
  SIGNAL product13                        : real := 0.0; -- double
  SIGNAL product12                        : real := 0.0; -- double
  SIGNAL product11                        : real := 0.0; -- double
  SIGNAL product10                        : real := 0.0; -- double
  SIGNAL product9                         : real := 0.0; -- double
  SIGNAL product8                         : real := 0.0; -- double
  SIGNAL product7                         : real := 0.0; -- double
  SIGNAL product6                         : real := 0.0; -- double
  SIGNAL product5                         : real := 0.0; -- double
  SIGNAL product4                         : real := 0.0; -- double
  SIGNAL product3                         : real := 0.0; -- double
  SIGNAL product2                         : real := 0.0; -- double
  SIGNAL product1                         : real := 0.0; -- double
  SIGNAL sum1_1                           : real := 0.0; -- double
  SIGNAL sum1_2                           : real := 0.0; -- double
  SIGNAL sum1_3                           : real := 0.0; -- double
  SIGNAL sum1_4                           : real := 0.0; -- double
  SIGNAL sum1_5                           : real := 0.0; -- double
  SIGNAL sum1_6                           : real := 0.0; -- double
  SIGNAL sum1_7                           : real := 0.0; -- double
  SIGNAL sum1_8                           : real := 0.0; -- double
  SIGNAL sum1_9                           : real := 0.0; -- double
  SIGNAL sum1_10                          : real := 0.0; -- double
  SIGNAL sum1_11                          : real := 0.0; -- double
  SIGNAL sum1_12                          : real := 0.0; -- double
  SIGNAL sum1_13                          : real := 0.0; -- double
  SIGNAL sum1_14                          : real := 0.0; -- double
  SIGNAL sum1_15                          : real := 0.0; -- double
  SIGNAL sum1_16                          : real := 0.0; -- double
  SIGNAL sum1_17                          : real := 0.0; -- double
  SIGNAL sum1_18                          : real := 0.0; -- double
  SIGNAL sum1_19                          : real := 0.0; -- double
  SIGNAL sum1_20                          : real := 0.0; -- double
  SIGNAL sum1_21                          : real := 0.0; -- double
  SIGNAL sum1_22                          : real := 0.0; -- double
  SIGNAL sum1_23                          : real := 0.0; -- double
  SIGNAL sum1_24                          : real := 0.0; -- double
  SIGNAL sum1_25                          : real := 0.0; -- double
  SIGNAL sum1_26                          : real := 0.0; -- double
  SIGNAL sum1_27                          : real := 0.0; -- double
  SIGNAL sum1_28                          : real := 0.0; -- double
  SIGNAL sum1_29                          : real := 0.0; -- double
  SIGNAL sum1_30                          : real := 0.0; -- double
  SIGNAL sum1_31                          : real := 0.0; -- double
  SIGNAL sum1_32                          : real := 0.0; -- double
  SIGNAL sum1_33                          : real := 0.0; -- double
  SIGNAL sum1_34                          : real := 0.0; -- double
  SIGNAL sum1_35                          : real := 0.0; -- double
  SIGNAL sum1_36                          : real := 0.0; -- double
  SIGNAL sum1_37                          : real := 0.0; -- double
  SIGNAL sum1_38                          : real := 0.0; -- double
  SIGNAL sum1_39                          : real := 0.0; -- double
  SIGNAL sum1_40                          : real := 0.0; -- double
  SIGNAL sum1_41                          : real := 0.0; -- double
  SIGNAL sum1_42                          : real := 0.0; -- double
  SIGNAL sum1_43                          : real := 0.0; -- double
  SIGNAL sum1_44                          : real := 0.0; -- double
  SIGNAL sum1_45                          : real := 0.0; -- double
  SIGNAL sum1_46                          : real := 0.0; -- double
  SIGNAL sum1_47                          : real := 0.0; -- double
  SIGNAL sum1_48                          : real := 0.0; -- double
  SIGNAL sum1_49                          : real := 0.0; -- double
  SIGNAL sum1_50                          : real := 0.0; -- double
  SIGNAL sum1_51                          : real := 0.0; -- double
  SIGNAL sum1_52                          : real := 0.0; -- double
  SIGNAL sum1_53                          : real := 0.0; -- double
  SIGNAL sum1_54                          : real := 0.0; -- double
  SIGNAL sum1_55                          : real := 0.0; -- double
  SIGNAL sum1_56                          : real := 0.0; -- double
  SIGNAL sum1_57                          : real := 0.0; -- double
  SIGNAL sum1_58                          : real := 0.0; -- double
  SIGNAL sum1_59                          : real := 0.0; -- double
  SIGNAL sum1_60                          : real := 0.0; -- double
  SIGNAL sum1_61                          : real := 0.0; -- double
  SIGNAL sum2_1                           : real := 0.0; -- double
  SIGNAL sum2_2                           : real := 0.0; -- double
  SIGNAL sum2_3                           : real := 0.0; -- double
  SIGNAL sum2_4                           : real := 0.0; -- double
  SIGNAL sum2_5                           : real := 0.0; -- double
  SIGNAL sum2_6                           : real := 0.0; -- double
  SIGNAL sum2_7                           : real := 0.0; -- double
  SIGNAL sum2_8                           : real := 0.0; -- double
  SIGNAL sum2_9                           : real := 0.0; -- double
  SIGNAL sum2_10                          : real := 0.0; -- double
  SIGNAL sum2_11                          : real := 0.0; -- double
  SIGNAL sum2_12                          : real := 0.0; -- double
  SIGNAL sum2_13                          : real := 0.0; -- double
  SIGNAL sum2_14                          : real := 0.0; -- double
  SIGNAL sum2_15                          : real := 0.0; -- double
  SIGNAL sum2_16                          : real := 0.0; -- double
  SIGNAL sum2_17                          : real := 0.0; -- double
  SIGNAL sum2_18                          : real := 0.0; -- double
  SIGNAL sum2_19                          : real := 0.0; -- double
  SIGNAL sum2_20                          : real := 0.0; -- double
  SIGNAL sum2_21                          : real := 0.0; -- double
  SIGNAL sum2_22                          : real := 0.0; -- double
  SIGNAL sum2_23                          : real := 0.0; -- double
  SIGNAL sum2_24                          : real := 0.0; -- double
  SIGNAL sum2_25                          : real := 0.0; -- double
  SIGNAL sum2_26                          : real := 0.0; -- double
  SIGNAL sum2_27                          : real := 0.0; -- double
  SIGNAL sum2_28                          : real := 0.0; -- double
  SIGNAL sum2_29                          : real := 0.0; -- double
  SIGNAL sum2_30                          : real := 0.0; -- double
  SIGNAL sum2_31                          : real := 0.0; -- double
  SIGNAL sum3_1                           : real := 0.0; -- double
  SIGNAL sum3_2                           : real := 0.0; -- double
  SIGNAL sum3_3                           : real := 0.0; -- double
  SIGNAL sum3_4                           : real := 0.0; -- double
  SIGNAL sum3_5                           : real := 0.0; -- double
  SIGNAL sum3_6                           : real := 0.0; -- double
  SIGNAL sum3_7                           : real := 0.0; -- double
  SIGNAL sum3_8                           : real := 0.0; -- double
  SIGNAL sum3_9                           : real := 0.0; -- double
  SIGNAL sum3_10                          : real := 0.0; -- double
  SIGNAL sum3_11                          : real := 0.0; -- double
  SIGNAL sum3_12                          : real := 0.0; -- double
  SIGNAL sum3_13                          : real := 0.0; -- double
  SIGNAL sum3_14                          : real := 0.0; -- double
  SIGNAL sum3_15                          : real := 0.0; -- double
  SIGNAL sum4_1                           : real := 0.0; -- double
  SIGNAL sum4_2                           : real := 0.0; -- double
  SIGNAL sum4_3                           : real := 0.0; -- double
  SIGNAL sum4_4                           : real := 0.0; -- double
  SIGNAL sum4_5                           : real := 0.0; -- double
  SIGNAL sum4_6                           : real := 0.0; -- double
  SIGNAL sum4_7                           : real := 0.0; -- double
  SIGNAL sum4_8                           : real := 0.0; -- double
  SIGNAL sum5_1                           : real := 0.0; -- double
  SIGNAL sum5_2                           : real := 0.0; -- double
  SIGNAL sum5_3                           : real := 0.0; -- double
  SIGNAL sum5_4                           : real := 0.0; -- double
  SIGNAL sum6_1                           : real := 0.0; -- double
  SIGNAL sum6_2                           : real := 0.0; -- double
  SIGNAL sum7_1                           : real := 0.0; -- double
  SIGNAL output_register                  : real := 0.0; -- double


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 122) <= (OTHERS => 0.0000000000000000E+00);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= filter_in;
        delay_pipeline(1 TO 122) <= delay_pipeline(0 TO 121);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  product123 <= delay_pipeline(122) * coeff123;

  product122 <= delay_pipeline(121) * coeff122;

  product121 <= delay_pipeline(120) * coeff121;

  product120 <= delay_pipeline(119) * coeff120;

  product119 <= delay_pipeline(118) * coeff119;

  product118 <= delay_pipeline(117) * coeff118;

  product117 <= delay_pipeline(116) * coeff117;

  product116 <= delay_pipeline(115) * coeff116;

  product115 <= delay_pipeline(114) * coeff115;

  product114 <= delay_pipeline(113) * coeff114;

  product113 <= delay_pipeline(112) * coeff113;

  product112 <= delay_pipeline(111) * coeff112;

  product111 <= delay_pipeline(110) * coeff111;

  product110 <= delay_pipeline(109) * coeff110;

  product109 <= delay_pipeline(108) * coeff109;

  product108 <= delay_pipeline(107) * coeff108;

  product107 <= delay_pipeline(106) * coeff107;

  product106 <= delay_pipeline(105) * coeff106;

  product105 <= delay_pipeline(104) * coeff105;

  product104 <= delay_pipeline(103) * coeff104;

  product103 <= delay_pipeline(102) * coeff103;

  product102 <= delay_pipeline(101) * coeff102;

  product101 <= delay_pipeline(100) * coeff101;

  product100 <= delay_pipeline(99) * coeff100;

  product99 <= delay_pipeline(98) * coeff99;

  product98 <= delay_pipeline(97) * coeff98;

  product97 <= delay_pipeline(96) * coeff97;

  product96 <= delay_pipeline(95) * coeff96;

  product95 <= delay_pipeline(94) * coeff95;

  product94 <= delay_pipeline(93) * coeff94;

  product93 <= delay_pipeline(92) * coeff93;

  product92 <= delay_pipeline(91) * coeff92;

  product91 <= delay_pipeline(90) * coeff91;

  product90 <= delay_pipeline(89) * coeff90;

  product89 <= delay_pipeline(88) * coeff89;

  product88 <= delay_pipeline(87) * coeff88;

  product87 <= delay_pipeline(86) * coeff87;

  product86 <= delay_pipeline(85) * coeff86;

  product85 <= delay_pipeline(84) * coeff85;

  product84 <= delay_pipeline(83) * coeff84;

  product83 <= delay_pipeline(82) * coeff83;

  product82 <= delay_pipeline(81) * coeff82;

  product81 <= delay_pipeline(80) * coeff81;

  product80 <= delay_pipeline(79) * coeff80;

  product79 <= delay_pipeline(78) * coeff79;

  product78 <= delay_pipeline(77) * coeff78;

  product77 <= delay_pipeline(76) * coeff77;

  product76 <= delay_pipeline(75) * coeff76;

  product75 <= delay_pipeline(74) * coeff75;

  product74 <= delay_pipeline(73) * coeff74;

  product73 <= delay_pipeline(72) * coeff73;

  product72 <= delay_pipeline(71) * coeff72;

  product71 <= delay_pipeline(70) * coeff71;

  product70 <= delay_pipeline(69) * coeff70;

  product69 <= delay_pipeline(68) * coeff69;

  product68 <= delay_pipeline(67) * coeff68;

  product67 <= delay_pipeline(66) * coeff67;

  product66 <= delay_pipeline(65) * coeff66;

  product65 <= delay_pipeline(64) * coeff65;

  product64 <= delay_pipeline(63) * coeff64;

  product63 <= delay_pipeline(62) * coeff63;

  product62 <= delay_pipeline(61) * coeff62;

  product61 <= delay_pipeline(60) * coeff61;

  product60 <= delay_pipeline(59) * coeff60;

  product59 <= delay_pipeline(58) * coeff59;

  product58 <= delay_pipeline(57) * coeff58;

  product57 <= delay_pipeline(56) * coeff57;

  product56 <= delay_pipeline(55) * coeff56;

  product55 <= delay_pipeline(54) * coeff55;

  product54 <= delay_pipeline(53) * coeff54;

  product53 <= delay_pipeline(52) * coeff53;

  product52 <= delay_pipeline(51) * coeff52;

  product51 <= delay_pipeline(50) * coeff51;

  product50 <= delay_pipeline(49) * coeff50;

  product49 <= delay_pipeline(48) * coeff49;

  product48 <= delay_pipeline(47) * coeff48;

  product47 <= delay_pipeline(46) * coeff47;

  product46 <= delay_pipeline(45) * coeff46;

  product45 <= delay_pipeline(44) * coeff45;

  product44 <= delay_pipeline(43) * coeff44;

  product43 <= delay_pipeline(42) * coeff43;

  product42 <= delay_pipeline(41) * coeff42;

  product41 <= delay_pipeline(40) * coeff41;

  product40 <= delay_pipeline(39) * coeff40;

  product39 <= delay_pipeline(38) * coeff39;

  product38 <= delay_pipeline(37) * coeff38;

  product37 <= delay_pipeline(36) * coeff37;

  product36 <= delay_pipeline(35) * coeff36;

  product35 <= delay_pipeline(34) * coeff35;

  product34 <= delay_pipeline(33) * coeff34;

  product33 <= delay_pipeline(32) * coeff33;

  product32 <= delay_pipeline(31) * coeff32;

  product31 <= delay_pipeline(30) * coeff31;

  product30 <= delay_pipeline(29) * coeff30;

  product29 <= delay_pipeline(28) * coeff29;

  product28 <= delay_pipeline(27) * coeff28;

  product27 <= delay_pipeline(26) * coeff27;

  product26 <= delay_pipeline(25) * coeff26;

  product25 <= delay_pipeline(24) * coeff25;

  product24 <= delay_pipeline(23) * coeff24;

  product23 <= delay_pipeline(22) * coeff23;

  product22 <= delay_pipeline(21) * coeff22;

  product21 <= delay_pipeline(20) * coeff21;

  product20 <= delay_pipeline(19) * coeff20;

  product19 <= delay_pipeline(18) * coeff19;

  product18 <= delay_pipeline(17) * coeff18;

  product17 <= delay_pipeline(16) * coeff17;

  product16 <= delay_pipeline(15) * coeff16;

  product15 <= delay_pipeline(14) * coeff15;

  product14 <= delay_pipeline(13) * coeff14;

  product13 <= delay_pipeline(12) * coeff13;

  product12 <= delay_pipeline(11) * coeff12;

  product11 <= delay_pipeline(10) * coeff11;

  product10 <= delay_pipeline(9) * coeff10;

  product9 <= delay_pipeline(8) * coeff9;

  product8 <= delay_pipeline(7) * coeff8;

  product7 <= delay_pipeline(6) * coeff7;

  product6 <= delay_pipeline(5) * coeff6;

  product5 <= delay_pipeline(4) * coeff5;

  product4 <= delay_pipeline(3) * coeff4;

  product3 <= delay_pipeline(2) * coeff3;

  product2 <= delay_pipeline(1) * coeff2;

  product1 <= delay_pipeline(0) * coeff1;

  sum1_1 <= product123 + product122;

  sum1_2 <= product121 + product120;

  sum1_3 <= product119 + product118;

  sum1_4 <= product117 + product116;

  sum1_5 <= product115 + product114;

  sum1_6 <= product113 + product112;

  sum1_7 <= product111 + product110;

  sum1_8 <= product109 + product108;

  sum1_9 <= product107 + product106;

  sum1_10 <= product105 + product104;

  sum1_11 <= product103 + product102;

  sum1_12 <= product101 + product100;

  sum1_13 <= product99 + product98;

  sum1_14 <= product97 + product96;

  sum1_15 <= product95 + product94;

  sum1_16 <= product93 + product92;

  sum1_17 <= product91 + product90;

  sum1_18 <= product89 + product88;

  sum1_19 <= product87 + product86;

  sum1_20 <= product85 + product84;

  sum1_21 <= product83 + product82;

  sum1_22 <= product81 + product80;

  sum1_23 <= product79 + product78;

  sum1_24 <= product77 + product76;

  sum1_25 <= product75 + product74;

  sum1_26 <= product73 + product72;

  sum1_27 <= product71 + product70;

  sum1_28 <= product69 + product68;

  sum1_29 <= product67 + product66;

  sum1_30 <= product65 + product64;

  sum1_31 <= product63 + product62;

  sum1_32 <= product61 + product60;

  sum1_33 <= product59 + product58;

  sum1_34 <= product57 + product56;

  sum1_35 <= product55 + product54;

  sum1_36 <= product53 + product52;

  sum1_37 <= product51 + product50;

  sum1_38 <= product49 + product48;

  sum1_39 <= product47 + product46;

  sum1_40 <= product45 + product44;

  sum1_41 <= product43 + product42;

  sum1_42 <= product41 + product40;

  sum1_43 <= product39 + product38;

  sum1_44 <= product37 + product36;

  sum1_45 <= product35 + product34;

  sum1_46 <= product33 + product32;

  sum1_47 <= product31 + product30;

  sum1_48 <= product29 + product28;

  sum1_49 <= product27 + product26;

  sum1_50 <= product25 + product24;

  sum1_51 <= product23 + product22;

  sum1_52 <= product21 + product20;

  sum1_53 <= product19 + product18;

  sum1_54 <= product17 + product16;

  sum1_55 <= product15 + product14;

  sum1_56 <= product13 + product12;

  sum1_57 <= product11 + product10;

  sum1_58 <= product9 + product8;

  sum1_59 <= product7 + product6;

  sum1_60 <= product5 + product4;

  sum1_61 <= product3 + product2;

  sum2_1 <= sum1_1 + sum1_2;

  sum2_2 <= sum1_3 + sum1_4;

  sum2_3 <= sum1_5 + sum1_6;

  sum2_4 <= sum1_7 + sum1_8;

  sum2_5 <= sum1_9 + sum1_10;

  sum2_6 <= sum1_11 + sum1_12;

  sum2_7 <= sum1_13 + sum1_14;

  sum2_8 <= sum1_15 + sum1_16;

  sum2_9 <= sum1_17 + sum1_18;

  sum2_10 <= sum1_19 + sum1_20;

  sum2_11 <= sum1_21 + sum1_22;

  sum2_12 <= sum1_23 + sum1_24;

  sum2_13 <= sum1_25 + sum1_26;

  sum2_14 <= sum1_27 + sum1_28;

  sum2_15 <= sum1_29 + sum1_30;

  sum2_16 <= sum1_31 + sum1_32;

  sum2_17 <= sum1_33 + sum1_34;

  sum2_18 <= sum1_35 + sum1_36;

  sum2_19 <= sum1_37 + sum1_38;

  sum2_20 <= sum1_39 + sum1_40;

  sum2_21 <= sum1_41 + sum1_42;

  sum2_22 <= sum1_43 + sum1_44;

  sum2_23 <= sum1_45 + sum1_46;

  sum2_24 <= sum1_47 + sum1_48;

  sum2_25 <= sum1_49 + sum1_50;

  sum2_26 <= sum1_51 + sum1_52;

  sum2_27 <= sum1_53 + sum1_54;

  sum2_28 <= sum1_55 + sum1_56;

  sum2_29 <= sum1_57 + sum1_58;

  sum2_30 <= sum1_59 + sum1_60;

  sum2_31 <= sum1_61 + product1;

  sum3_1 <= sum2_1 + sum2_2;

  sum3_2 <= sum2_3 + sum2_4;

  sum3_3 <= sum2_5 + sum2_6;

  sum3_4 <= sum2_7 + sum2_8;

  sum3_5 <= sum2_9 + sum2_10;

  sum3_6 <= sum2_11 + sum2_12;

  sum3_7 <= sum2_13 + sum2_14;

  sum3_8 <= sum2_15 + sum2_16;

  sum3_9 <= sum2_17 + sum2_18;

  sum3_10 <= sum2_19 + sum2_20;

  sum3_11 <= sum2_21 + sum2_22;

  sum3_12 <= sum2_23 + sum2_24;

  sum3_13 <= sum2_25 + sum2_26;

  sum3_14 <= sum2_27 + sum2_28;

  sum3_15 <= sum2_29 + sum2_30;

  sum4_1 <= sum3_1 + sum3_2;

  sum4_2 <= sum3_3 + sum3_4;

  sum4_3 <= sum3_5 + sum3_6;

  sum4_4 <= sum3_7 + sum3_8;

  sum4_5 <= sum3_9 + sum3_10;

  sum4_6 <= sum3_11 + sum3_12;

  sum4_7 <= sum3_13 + sum3_14;

  sum4_8 <= sum3_15 + sum2_31;

  sum5_1 <= sum4_1 + sum4_2;

  sum5_2 <= sum4_3 + sum4_4;

  sum5_3 <= sum4_5 + sum4_6;

  sum5_4 <= sum4_7 + sum4_8;

  sum6_1 <= sum5_1 + sum5_2;

  sum6_2 <= sum5_3 + sum5_4;

  sum7_1 <= sum6_1 + sum6_2;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= sum7_1;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= output_register;
END rtl;
