-- -------------------------------------------------------------
--
-- Module: filter
-- Generated by MATLAB(R) 9.1 and the Filter Design HDL Coder 3.1.
-- Generated on: 2020-06-19 00:15:08
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- TargetDirectory: C:\LUCIANO\TESIS\ADS8694_Handler\ADS8694_Handler\ADS8694_Handler\src
-- TestBenchStimulus: step ramp chirp 

-- Filter Specifications:
--
-- Sample Rate     : N/A (normalized frequency)
-- Response        : Lowpass
-- Specification   : Fp,Fst,Ap,Ast
-- Stopband Edge   : 0.006
-- Stopband Atten. : 40 dB
-- Passband Edge   : 0.003
-- Passband Ripple : 1 dB
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time IIR Filter (real)
-- -------------------------------
-- Filter Structure    : Direct-Form II, Second-Order Sections
-- Number of Sections  : 4
-- Stable              : Yes
-- Linear Phase        : No
-- Arithmetic          : fixed
-- Numerator           : s32,29 -> [-4 4)
-- Denominator         : s32,30 -> [-2 2)
-- Scale Values        : s32,30 -> [-2 2)
-- Input               : s19,0 -> [-262144 262144)
-- Section Input       : s72,25 -> [-70368744177664 70368744177664)
-- Section Output      : s70,25 -> [-17592186044416 17592186044416)
-- Output              : s19,0 -> [-262144 262144)
-- State               : s50,10 -> [-549755813888 549755813888)
-- Numerator Prod      : s82,39 -> [-4398046511104 4398046511104)
-- Denominator Prod    : s82,40 -> [-2199023255552 2199023255552)
-- Numerator Accum     : s70,25 -> [-17592186044416 17592186044416)
-- Denominator Accum   : s70,26 -> [-8796093022208 8796093022208)
-- Round Mode          : convergent
-- Overflow Mode       : wrap
-- Cast Before Sum     : true
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(18 DOWNTO 0); -- sfix19
         filter_out                      :   OUT   std_logic_vector(18 DOWNTO 0)  -- sfix19
         );

END filter;


----------------------------------------------------------------
--Module Architecture: filter
----------------------------------------------------------------
ARCHITECTURE rtl OF filter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(49 DOWNTO 0); -- sfix50_En10
  -- Constants
  CONSTANT scaleconst1                    : signed(31 DOWNTO 0) := to_signed(30100, 32); -- sfix32_En30
  CONSTANT coeff_b1_section1              : signed(31 DOWNTO 0) := to_signed(536870912, 32); -- sfix32_En29
  CONSTANT coeff_b2_section1              : signed(31 DOWNTO 0) := to_signed(1073741824, 32); -- sfix32_En29
  CONSTANT coeff_b3_section1              : signed(31 DOWNTO 0) := to_signed(536870912, 32); -- sfix32_En29
  CONSTANT coeff_a2_section1              : signed(31 DOWNTO 0) := to_signed(-2142931523, 32); -- sfix32_En30
  CONSTANT coeff_a3_section1              : signed(31 DOWNTO 0) := to_signed(1069310098, 32); -- sfix32_En30
  CONSTANT scaleconst2                    : signed(31 DOWNTO 0) := to_signed(29985, 32); -- sfix32_En30
  CONSTANT coeff_b1_section2              : signed(31 DOWNTO 0) := to_signed(536870912, 32); -- sfix32_En29
  CONSTANT coeff_b2_section2              : signed(31 DOWNTO 0) := to_signed(1073741824, 32); -- sfix32_En29
  CONSTANT coeff_b3_section2              : signed(31 DOWNTO 0) := to_signed(536870912, 32); -- sfix32_En29
  CONSTANT coeff_a2_section2              : signed(31 DOWNTO 0) := to_signed(-2134791159, 32); -- sfix32_En30
  CONSTANT coeff_a3_section2              : signed(31 DOWNTO 0) := to_signed(1061169277, 32); -- sfix32_En30
  CONSTANT scaleconst3                    : signed(31 DOWNTO 0) := to_signed(29899, 32); -- sfix32_En30
  CONSTANT coeff_b1_section3              : signed(31 DOWNTO 0) := to_signed(536870912, 32); -- sfix32_En29
  CONSTANT coeff_b2_section3              : signed(31 DOWNTO 0) := to_signed(1073741824, 32); -- sfix32_En29
  CONSTANT coeff_b3_section3              : signed(31 DOWNTO 0) := to_signed(536870912, 32); -- sfix32_En29
  CONSTANT coeff_a2_section3              : signed(31 DOWNTO 0) := to_signed(-2128602455, 32); -- sfix32_En30
  CONSTANT coeff_a3_section3              : signed(31 DOWNTO 0) := to_signed(1054980226, 32); -- sfix32_En30
  CONSTANT scaleconst4                    : signed(31 DOWNTO 0) := to_signed(29852, 32); -- sfix32_En30
  CONSTANT coeff_b1_section4              : signed(31 DOWNTO 0) := to_signed(536870912, 32); -- sfix32_En29
  CONSTANT coeff_b2_section4              : signed(31 DOWNTO 0) := to_signed(1073741824, 32); -- sfix32_En29
  CONSTANT coeff_b3_section4              : signed(31 DOWNTO 0) := to_signed(536870912, 32); -- sfix32_En29
  CONSTANT coeff_a2_section4              : signed(31 DOWNTO 0) := to_signed(-2125268094, 32); -- sfix32_En30
  CONSTANT coeff_a3_section4              : signed(31 DOWNTO 0) := to_signed(1051645677, 32); -- sfix32_En30
  -- Signals
  SIGNAL input_register                   : signed(18 DOWNTO 0); -- sfix19
  SIGNAL scale1                           : signed(101 DOWNTO 0); -- sfix102_En55
  SIGNAL mul_temp                         : signed(50 DOWNTO 0); -- sfix51_En30
  SIGNAL scaletypeconvert1                : signed(71 DOWNTO 0); -- sfix72_En25
  -- Section 1 Signals 
  SIGNAL a1sum1                           : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL a2sum1                           : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL b1sum1                           : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL b2sum1                           : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL typeconvert1                     : signed(49 DOWNTO 0); -- sfix50_En10
  SIGNAL delay_section1                   : delay_pipeline_type(0 TO 1); -- sfix50_En10
  SIGNAL inputconv1                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL a2mul1                           : signed(81 DOWNTO 0); -- sfix82_En40
  SIGNAL a3mul1                           : signed(81 DOWNTO 0); -- sfix82_En40
  SIGNAL b1mul1                           : signed(81 DOWNTO 0); -- sfix82_En39
  SIGNAL b2mul1                           : signed(81 DOWNTO 0); -- sfix82_En39
  SIGNAL b3mul1                           : signed(81 DOWNTO 0); -- sfix82_En39
  SIGNAL sub_cast                         : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_cast_1                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_temp                         : signed(70 DOWNTO 0); -- sfix71_En26
  SIGNAL sub_cast_2                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_cast_3                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_temp_1                       : signed(70 DOWNTO 0); -- sfix71_En26
  SIGNAL b1multypeconvert1                : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_cast                         : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_cast_1                       : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_temp                         : signed(70 DOWNTO 0); -- sfix71_En25
  SIGNAL add_cast_2                       : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_cast_3                       : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_temp_1                       : signed(70 DOWNTO 0); -- sfix71_En25
  SIGNAL section_result1                  : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL scale2                           : signed(101 DOWNTO 0); -- sfix102_En55
  SIGNAL mul_temp_1                       : signed(101 DOWNTO 0); -- sfix102_En56
  SIGNAL scaletypeconvert2                : signed(71 DOWNTO 0); -- sfix72_En25
  -- Section 2 Signals 
  SIGNAL a1sum2                           : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL a2sum2                           : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL b1sum2                           : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL b2sum2                           : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL typeconvert2                     : signed(49 DOWNTO 0); -- sfix50_En10
  SIGNAL delay_section2                   : delay_pipeline_type(0 TO 1); -- sfix50_En10
  SIGNAL inputconv2                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL a2mul2                           : signed(81 DOWNTO 0); -- sfix82_En40
  SIGNAL a3mul2                           : signed(81 DOWNTO 0); -- sfix82_En40
  SIGNAL b1mul2                           : signed(81 DOWNTO 0); -- sfix82_En39
  SIGNAL b2mul2                           : signed(81 DOWNTO 0); -- sfix82_En39
  SIGNAL b3mul2                           : signed(81 DOWNTO 0); -- sfix82_En39
  SIGNAL sub_cast_4                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_cast_5                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_temp_2                       : signed(70 DOWNTO 0); -- sfix71_En26
  SIGNAL sub_cast_6                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_cast_7                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_temp_3                       : signed(70 DOWNTO 0); -- sfix71_En26
  SIGNAL b1multypeconvert2                : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_cast_4                       : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_cast_5                       : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_temp_2                       : signed(70 DOWNTO 0); -- sfix71_En25
  SIGNAL add_cast_6                       : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_cast_7                       : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_temp_3                       : signed(70 DOWNTO 0); -- sfix71_En25
  SIGNAL section_result2                  : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL scale3                           : signed(101 DOWNTO 0); -- sfix102_En55
  SIGNAL mul_temp_2                       : signed(101 DOWNTO 0); -- sfix102_En56
  SIGNAL scaletypeconvert3                : signed(71 DOWNTO 0); -- sfix72_En25
  -- Section 3 Signals 
  SIGNAL a1sum3                           : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL a2sum3                           : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL b1sum3                           : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL b2sum3                           : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL typeconvert3                     : signed(49 DOWNTO 0); -- sfix50_En10
  SIGNAL delay_section3                   : delay_pipeline_type(0 TO 1); -- sfix50_En10
  SIGNAL inputconv3                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL a2mul3                           : signed(81 DOWNTO 0); -- sfix82_En40
  SIGNAL a3mul3                           : signed(81 DOWNTO 0); -- sfix82_En40
  SIGNAL b1mul3                           : signed(81 DOWNTO 0); -- sfix82_En39
  SIGNAL b2mul3                           : signed(81 DOWNTO 0); -- sfix82_En39
  SIGNAL b3mul3                           : signed(81 DOWNTO 0); -- sfix82_En39
  SIGNAL sub_cast_8                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_cast_9                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_temp_4                       : signed(70 DOWNTO 0); -- sfix71_En26
  SIGNAL sub_cast_10                      : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_cast_11                      : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_temp_5                       : signed(70 DOWNTO 0); -- sfix71_En26
  SIGNAL b1multypeconvert3                : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_cast_8                       : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_cast_9                       : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_temp_4                       : signed(70 DOWNTO 0); -- sfix71_En25
  SIGNAL add_cast_10                      : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_cast_11                      : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_temp_5                       : signed(70 DOWNTO 0); -- sfix71_En25
  SIGNAL section_result3                  : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL scale4                           : signed(101 DOWNTO 0); -- sfix102_En55
  SIGNAL mul_temp_3                       : signed(101 DOWNTO 0); -- sfix102_En56
  SIGNAL scaletypeconvert4                : signed(71 DOWNTO 0); -- sfix72_En25
  -- Section 4 Signals 
  SIGNAL a1sum4                           : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL a2sum4                           : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL b1sum4                           : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL b2sum4                           : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL typeconvert4                     : signed(49 DOWNTO 0); -- sfix50_En10
  SIGNAL delay_section4                   : delay_pipeline_type(0 TO 1); -- sfix50_En10
  SIGNAL inputconv4                       : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL a2mul4                           : signed(81 DOWNTO 0); -- sfix82_En40
  SIGNAL a3mul4                           : signed(81 DOWNTO 0); -- sfix82_En40
  SIGNAL b1mul4                           : signed(81 DOWNTO 0); -- sfix82_En39
  SIGNAL b2mul4                           : signed(81 DOWNTO 0); -- sfix82_En39
  SIGNAL b3mul4                           : signed(81 DOWNTO 0); -- sfix82_En39
  SIGNAL sub_cast_12                      : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_cast_13                      : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_temp_6                       : signed(70 DOWNTO 0); -- sfix71_En26
  SIGNAL sub_cast_14                      : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_cast_15                      : signed(69 DOWNTO 0); -- sfix70_En26
  SIGNAL sub_temp_7                       : signed(70 DOWNTO 0); -- sfix71_En26
  SIGNAL b1multypeconvert4                : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_cast_12                      : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_cast_13                      : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_temp_6                       : signed(70 DOWNTO 0); -- sfix71_En25
  SIGNAL add_cast_14                      : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_cast_15                      : signed(69 DOWNTO 0); -- sfix70_En25
  SIGNAL add_temp_7                       : signed(70 DOWNTO 0); -- sfix71_En25
  SIGNAL output_typeconvert               : signed(18 DOWNTO 0); -- sfix19
  SIGNAL output_register                  : signed(18 DOWNTO 0); -- sfix19


BEGIN

  -- Block Statements
  input_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        input_register <= signed(filter_in);
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  mul_temp <= input_register * scaleconst1;
  scale1 <= resize(mul_temp(50 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 102);

  scaletypeconvert1 <= resize(shift_right(scale1(101 DOWNTO 0) + ( "0" & (scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30) & NOT scale1(30))), 30), 72);

  --   ------------------ Section 1 ------------------

  typeconvert1 <= resize(shift_right(a1sum1(65 DOWNTO 0) + ( "0" & (a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16) & NOT a1sum1(16))), 16), 50);

  delay_process_section1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section1 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section1(1) <= delay_section1(0);
        delay_section1(0) <= typeconvert1;
      END IF;
    END IF;
  END PROCESS delay_process_section1;

  inputconv1 <= resize(scaletypeconvert1(68 DOWNTO 0) & '0', 70);

  a2mul1 <= delay_section1(0) * coeff_a2_section1;

  a3mul1 <= delay_section1(1) * coeff_a3_section1;

  b1mul1 <= resize(typeconvert1(49 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 82);

  b2mul1 <= resize(delay_section1(0)(49 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 82);

  b3mul1 <= resize(delay_section1(1)(49 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 82);

  sub_cast <= inputconv1;
  sub_cast_1 <= resize(shift_right(a2mul1(81) & a2mul1(81 DOWNTO 0) + ( "0" & (a2mul1(14) & NOT a2mul1(14) & NOT a2mul1(14) & NOT a2mul1(14) & NOT a2mul1(14) & NOT a2mul1(14) & NOT a2mul1(14) & NOT a2mul1(14) & NOT a2mul1(14) & NOT a2mul1(14) & NOT a2mul1(14) & NOT a2mul1(14) & NOT a2mul1(14) & NOT a2mul1(14))), 14), 70);
  sub_temp <= resize(sub_cast, 71) - resize(sub_cast_1, 71);
  a2sum1 <= sub_temp(69 DOWNTO 0);

  sub_cast_2 <= a2sum1;
  sub_cast_3 <= resize(shift_right(a3mul1(81) & a3mul1(81 DOWNTO 0) + ( "0" & (a3mul1(14) & NOT a3mul1(14) & NOT a3mul1(14) & NOT a3mul1(14) & NOT a3mul1(14) & NOT a3mul1(14) & NOT a3mul1(14) & NOT a3mul1(14) & NOT a3mul1(14) & NOT a3mul1(14) & NOT a3mul1(14) & NOT a3mul1(14) & NOT a3mul1(14) & NOT a3mul1(14))), 14), 70);
  sub_temp_1 <= resize(sub_cast_2, 71) - resize(sub_cast_3, 71);
  a1sum1 <= sub_temp_1(69 DOWNTO 0);

  b1multypeconvert1 <= resize(shift_right(b1mul1(81) & b1mul1(81 DOWNTO 0) + ( "0" & (b1mul1(14) & NOT b1mul1(14) & NOT b1mul1(14) & NOT b1mul1(14) & NOT b1mul1(14) & NOT b1mul1(14) & NOT b1mul1(14) & NOT b1mul1(14) & NOT b1mul1(14) & NOT b1mul1(14) & NOT b1mul1(14) & NOT b1mul1(14) & NOT b1mul1(14) & NOT b1mul1(14))), 14), 70);

  add_cast <= b1multypeconvert1;
  add_cast_1 <= resize(shift_right(b2mul1(81) & b2mul1(81 DOWNTO 0) + ( "0" & (b2mul1(14) & NOT b2mul1(14) & NOT b2mul1(14) & NOT b2mul1(14) & NOT b2mul1(14) & NOT b2mul1(14) & NOT b2mul1(14) & NOT b2mul1(14) & NOT b2mul1(14) & NOT b2mul1(14) & NOT b2mul1(14) & NOT b2mul1(14) & NOT b2mul1(14) & NOT b2mul1(14))), 14), 70);
  add_temp <= resize(add_cast, 71) + resize(add_cast_1, 71);
  b2sum1 <= add_temp(69 DOWNTO 0);

  add_cast_2 <= b2sum1;
  add_cast_3 <= resize(shift_right(b3mul1(81) & b3mul1(81 DOWNTO 0) + ( "0" & (b3mul1(14) & NOT b3mul1(14) & NOT b3mul1(14) & NOT b3mul1(14) & NOT b3mul1(14) & NOT b3mul1(14) & NOT b3mul1(14) & NOT b3mul1(14) & NOT b3mul1(14) & NOT b3mul1(14) & NOT b3mul1(14) & NOT b3mul1(14) & NOT b3mul1(14) & NOT b3mul1(14))), 14), 70);
  add_temp_1 <= resize(add_cast_2, 71) + resize(add_cast_3, 71);
  b1sum1 <= add_temp_1(69 DOWNTO 0);

  section_result1 <= resize(b1sum1(68 DOWNTO 0) & '0', 70);

  mul_temp_1 <= section_result1 * scaleconst2;
  scale2 <= resize(shift_right(mul_temp_1(101) & mul_temp_1(101 DOWNTO 0) + ( "0" & (mul_temp_1(1))), 1), 102);

  scaletypeconvert2 <= resize(shift_right(scale2(101 DOWNTO 0) + ( "0" & (scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30) & NOT scale2(30))), 30), 72);

  --   ------------------ Section 2 ------------------

  typeconvert2 <= resize(shift_right(a1sum2(65 DOWNTO 0) + ( "0" & (a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16) & NOT a1sum2(16))), 16), 50);

  delay_process_section2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section2 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section2(1) <= delay_section2(0);
        delay_section2(0) <= typeconvert2;
      END IF;
    END IF;
  END PROCESS delay_process_section2;

  inputconv2 <= resize(scaletypeconvert2(68 DOWNTO 0) & '0', 70);

  a2mul2 <= delay_section2(0) * coeff_a2_section2;

  a3mul2 <= delay_section2(1) * coeff_a3_section2;

  b1mul2 <= resize(typeconvert2(49 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 82);

  b2mul2 <= resize(delay_section2(0)(49 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 82);

  b3mul2 <= resize(delay_section2(1)(49 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 82);

  sub_cast_4 <= inputconv2;
  sub_cast_5 <= resize(shift_right(a2mul2(81) & a2mul2(81 DOWNTO 0) + ( "0" & (a2mul2(14) & NOT a2mul2(14) & NOT a2mul2(14) & NOT a2mul2(14) & NOT a2mul2(14) & NOT a2mul2(14) & NOT a2mul2(14) & NOT a2mul2(14) & NOT a2mul2(14) & NOT a2mul2(14) & NOT a2mul2(14) & NOT a2mul2(14) & NOT a2mul2(14) & NOT a2mul2(14))), 14), 70);
  sub_temp_2 <= resize(sub_cast_4, 71) - resize(sub_cast_5, 71);
  a2sum2 <= sub_temp_2(69 DOWNTO 0);

  sub_cast_6 <= a2sum2;
  sub_cast_7 <= resize(shift_right(a3mul2(81) & a3mul2(81 DOWNTO 0) + ( "0" & (a3mul2(14) & NOT a3mul2(14) & NOT a3mul2(14) & NOT a3mul2(14) & NOT a3mul2(14) & NOT a3mul2(14) & NOT a3mul2(14) & NOT a3mul2(14) & NOT a3mul2(14) & NOT a3mul2(14) & NOT a3mul2(14) & NOT a3mul2(14) & NOT a3mul2(14) & NOT a3mul2(14))), 14), 70);
  sub_temp_3 <= resize(sub_cast_6, 71) - resize(sub_cast_7, 71);
  a1sum2 <= sub_temp_3(69 DOWNTO 0);

  b1multypeconvert2 <= resize(shift_right(b1mul2(81) & b1mul2(81 DOWNTO 0) + ( "0" & (b1mul2(14) & NOT b1mul2(14) & NOT b1mul2(14) & NOT b1mul2(14) & NOT b1mul2(14) & NOT b1mul2(14) & NOT b1mul2(14) & NOT b1mul2(14) & NOT b1mul2(14) & NOT b1mul2(14) & NOT b1mul2(14) & NOT b1mul2(14) & NOT b1mul2(14) & NOT b1mul2(14))), 14), 70);

  add_cast_4 <= b1multypeconvert2;
  add_cast_5 <= resize(shift_right(b2mul2(81) & b2mul2(81 DOWNTO 0) + ( "0" & (b2mul2(14) & NOT b2mul2(14) & NOT b2mul2(14) & NOT b2mul2(14) & NOT b2mul2(14) & NOT b2mul2(14) & NOT b2mul2(14) & NOT b2mul2(14) & NOT b2mul2(14) & NOT b2mul2(14) & NOT b2mul2(14) & NOT b2mul2(14) & NOT b2mul2(14) & NOT b2mul2(14))), 14), 70);
  add_temp_2 <= resize(add_cast_4, 71) + resize(add_cast_5, 71);
  b2sum2 <= add_temp_2(69 DOWNTO 0);

  add_cast_6 <= b2sum2;
  add_cast_7 <= resize(shift_right(b3mul2(81) & b3mul2(81 DOWNTO 0) + ( "0" & (b3mul2(14) & NOT b3mul2(14) & NOT b3mul2(14) & NOT b3mul2(14) & NOT b3mul2(14) & NOT b3mul2(14) & NOT b3mul2(14) & NOT b3mul2(14) & NOT b3mul2(14) & NOT b3mul2(14) & NOT b3mul2(14) & NOT b3mul2(14) & NOT b3mul2(14) & NOT b3mul2(14))), 14), 70);
  add_temp_3 <= resize(add_cast_6, 71) + resize(add_cast_7, 71);
  b1sum2 <= add_temp_3(69 DOWNTO 0);

  section_result2 <= resize(b1sum2(68 DOWNTO 0) & '0', 70);

  mul_temp_2 <= section_result2 * scaleconst3;
  scale3 <= resize(shift_right(mul_temp_2(101) & mul_temp_2(101 DOWNTO 0) + ( "0" & (mul_temp_2(1))), 1), 102);

  scaletypeconvert3 <= resize(shift_right(scale3(101 DOWNTO 0) + ( "0" & (scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30) & NOT scale3(30))), 30), 72);

  --   ------------------ Section 3 ------------------

  typeconvert3 <= resize(shift_right(a1sum3(65 DOWNTO 0) + ( "0" & (a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16) & NOT a1sum3(16))), 16), 50);

  delay_process_section3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section3 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section3(1) <= delay_section3(0);
        delay_section3(0) <= typeconvert3;
      END IF;
    END IF;
  END PROCESS delay_process_section3;

  inputconv3 <= resize(scaletypeconvert3(68 DOWNTO 0) & '0', 70);

  a2mul3 <= delay_section3(0) * coeff_a2_section3;

  a3mul3 <= delay_section3(1) * coeff_a3_section3;

  b1mul3 <= resize(typeconvert3(49 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 82);

  b2mul3 <= resize(delay_section3(0)(49 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 82);

  b3mul3 <= resize(delay_section3(1)(49 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 82);

  sub_cast_8 <= inputconv3;
  sub_cast_9 <= resize(shift_right(a2mul3(81) & a2mul3(81 DOWNTO 0) + ( "0" & (a2mul3(14) & NOT a2mul3(14) & NOT a2mul3(14) & NOT a2mul3(14) & NOT a2mul3(14) & NOT a2mul3(14) & NOT a2mul3(14) & NOT a2mul3(14) & NOT a2mul3(14) & NOT a2mul3(14) & NOT a2mul3(14) & NOT a2mul3(14) & NOT a2mul3(14) & NOT a2mul3(14))), 14), 70);
  sub_temp_4 <= resize(sub_cast_8, 71) - resize(sub_cast_9, 71);
  a2sum3 <= sub_temp_4(69 DOWNTO 0);

  sub_cast_10 <= a2sum3;
  sub_cast_11 <= resize(shift_right(a3mul3(81) & a3mul3(81 DOWNTO 0) + ( "0" & (a3mul3(14) & NOT a3mul3(14) & NOT a3mul3(14) & NOT a3mul3(14) & NOT a3mul3(14) & NOT a3mul3(14) & NOT a3mul3(14) & NOT a3mul3(14) & NOT a3mul3(14) & NOT a3mul3(14) & NOT a3mul3(14) & NOT a3mul3(14) & NOT a3mul3(14) & NOT a3mul3(14))), 14), 70);
  sub_temp_5 <= resize(sub_cast_10, 71) - resize(sub_cast_11, 71);
  a1sum3 <= sub_temp_5(69 DOWNTO 0);

  b1multypeconvert3 <= resize(shift_right(b1mul3(81) & b1mul3(81 DOWNTO 0) + ( "0" & (b1mul3(14) & NOT b1mul3(14) & NOT b1mul3(14) & NOT b1mul3(14) & NOT b1mul3(14) & NOT b1mul3(14) & NOT b1mul3(14) & NOT b1mul3(14) & NOT b1mul3(14) & NOT b1mul3(14) & NOT b1mul3(14) & NOT b1mul3(14) & NOT b1mul3(14) & NOT b1mul3(14))), 14), 70);

  add_cast_8 <= b1multypeconvert3;
  add_cast_9 <= resize(shift_right(b2mul3(81) & b2mul3(81 DOWNTO 0) + ( "0" & (b2mul3(14) & NOT b2mul3(14) & NOT b2mul3(14) & NOT b2mul3(14) & NOT b2mul3(14) & NOT b2mul3(14) & NOT b2mul3(14) & NOT b2mul3(14) & NOT b2mul3(14) & NOT b2mul3(14) & NOT b2mul3(14) & NOT b2mul3(14) & NOT b2mul3(14) & NOT b2mul3(14))), 14), 70);
  add_temp_4 <= resize(add_cast_8, 71) + resize(add_cast_9, 71);
  b2sum3 <= add_temp_4(69 DOWNTO 0);

  add_cast_10 <= b2sum3;
  add_cast_11 <= resize(shift_right(b3mul3(81) & b3mul3(81 DOWNTO 0) + ( "0" & (b3mul3(14) & NOT b3mul3(14) & NOT b3mul3(14) & NOT b3mul3(14) & NOT b3mul3(14) & NOT b3mul3(14) & NOT b3mul3(14) & NOT b3mul3(14) & NOT b3mul3(14) & NOT b3mul3(14) & NOT b3mul3(14) & NOT b3mul3(14) & NOT b3mul3(14) & NOT b3mul3(14))), 14), 70);
  add_temp_5 <= resize(add_cast_10, 71) + resize(add_cast_11, 71);
  b1sum3 <= add_temp_5(69 DOWNTO 0);

  section_result3 <= resize(b1sum3(68 DOWNTO 0) & '0', 70);

  mul_temp_3 <= section_result3 * scaleconst4;
  scale4 <= resize(shift_right(mul_temp_3(101) & mul_temp_3(101 DOWNTO 0) + ( "0" & (mul_temp_3(1))), 1), 102);

  scaletypeconvert4 <= resize(shift_right(scale4(101 DOWNTO 0) + ( "0" & (scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30) & NOT scale4(30))), 30), 72);

  --   ------------------ Section 4 ------------------

  typeconvert4 <= resize(shift_right(a1sum4(65 DOWNTO 0) + ( "0" & (a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16) & NOT a1sum4(16))), 16), 50);

  delay_process_section4 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section4 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section4(1) <= delay_section4(0);
        delay_section4(0) <= typeconvert4;
      END IF;
    END IF;
  END PROCESS delay_process_section4;

  inputconv4 <= resize(scaletypeconvert4(68 DOWNTO 0) & '0', 70);

  a2mul4 <= delay_section4(0) * coeff_a2_section4;

  a3mul4 <= delay_section4(1) * coeff_a3_section4;

  b1mul4 <= resize(typeconvert4(49 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 82);

  b2mul4 <= resize(delay_section4(0)(49 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 82);

  b3mul4 <= resize(delay_section4(1)(49 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 82);

  sub_cast_12 <= inputconv4;
  sub_cast_13 <= resize(shift_right(a2mul4(81) & a2mul4(81 DOWNTO 0) + ( "0" & (a2mul4(14) & NOT a2mul4(14) & NOT a2mul4(14) & NOT a2mul4(14) & NOT a2mul4(14) & NOT a2mul4(14) & NOT a2mul4(14) & NOT a2mul4(14) & NOT a2mul4(14) & NOT a2mul4(14) & NOT a2mul4(14) & NOT a2mul4(14) & NOT a2mul4(14) & NOT a2mul4(14))), 14), 70);
  sub_temp_6 <= resize(sub_cast_12, 71) - resize(sub_cast_13, 71);
  a2sum4 <= sub_temp_6(69 DOWNTO 0);

  sub_cast_14 <= a2sum4;
  sub_cast_15 <= resize(shift_right(a3mul4(81) & a3mul4(81 DOWNTO 0) + ( "0" & (a3mul4(14) & NOT a3mul4(14) & NOT a3mul4(14) & NOT a3mul4(14) & NOT a3mul4(14) & NOT a3mul4(14) & NOT a3mul4(14) & NOT a3mul4(14) & NOT a3mul4(14) & NOT a3mul4(14) & NOT a3mul4(14) & NOT a3mul4(14) & NOT a3mul4(14) & NOT a3mul4(14))), 14), 70);
  sub_temp_7 <= resize(sub_cast_14, 71) - resize(sub_cast_15, 71);
  a1sum4 <= sub_temp_7(69 DOWNTO 0);

  b1multypeconvert4 <= resize(shift_right(b1mul4(81) & b1mul4(81 DOWNTO 0) + ( "0" & (b1mul4(14) & NOT b1mul4(14) & NOT b1mul4(14) & NOT b1mul4(14) & NOT b1mul4(14) & NOT b1mul4(14) & NOT b1mul4(14) & NOT b1mul4(14) & NOT b1mul4(14) & NOT b1mul4(14) & NOT b1mul4(14) & NOT b1mul4(14) & NOT b1mul4(14) & NOT b1mul4(14))), 14), 70);

  add_cast_12 <= b1multypeconvert4;
  add_cast_13 <= resize(shift_right(b2mul4(81) & b2mul4(81 DOWNTO 0) + ( "0" & (b2mul4(14) & NOT b2mul4(14) & NOT b2mul4(14) & NOT b2mul4(14) & NOT b2mul4(14) & NOT b2mul4(14) & NOT b2mul4(14) & NOT b2mul4(14) & NOT b2mul4(14) & NOT b2mul4(14) & NOT b2mul4(14) & NOT b2mul4(14) & NOT b2mul4(14) & NOT b2mul4(14))), 14), 70);
  add_temp_6 <= resize(add_cast_12, 71) + resize(add_cast_13, 71);
  b2sum4 <= add_temp_6(69 DOWNTO 0);

  add_cast_14 <= b2sum4;
  add_cast_15 <= resize(shift_right(b3mul4(81) & b3mul4(81 DOWNTO 0) + ( "0" & (b3mul4(14) & NOT b3mul4(14) & NOT b3mul4(14) & NOT b3mul4(14) & NOT b3mul4(14) & NOT b3mul4(14) & NOT b3mul4(14) & NOT b3mul4(14) & NOT b3mul4(14) & NOT b3mul4(14) & NOT b3mul4(14) & NOT b3mul4(14) & NOT b3mul4(14) & NOT b3mul4(14))), 14), 70);
  add_temp_7 <= resize(add_cast_14, 71) + resize(add_cast_15, 71);
  b1sum4 <= add_temp_7(69 DOWNTO 0);

  output_typeconvert <= resize(shift_right(b1sum4(43 DOWNTO 0) + ( "0" & (b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25) & NOT b1sum4(25))), 25), 19);

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
